### PR TITLE
rename to sensu-extensions-influxdb2

### LINKED ISSUE #4: Rename sensu-extensions-influxdb to sensu-extensions-influxdb2
I'm not quite sure how to formulate this because i'm really quite new to sensu but trying to load this extension crashes my instance. I tried to follow the readme file to the letter.

Using sensu 0.29.0-11 on Debian Jessie.

Here is the end of the sensu-server log, please tell me if i can do anything else.
```json
{"timestamp":"2017-07-05T15:05:53.984292+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2017-07-05T15:05:53.984503+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-influxdb","version":null}
{"timestamp":"2017-07-05T15:05:53.984540+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/influxdb"}
{"timestamp":"2017-07-05T15:05:53.984563+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-history","version":null}
{"timestamp":"2017-07-05T15:05:53.984587+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/history"}
{"timestamp":"2017-07-05T15:05:53.984606+0000","level":"warn","message":"failed to require extension","gem":"sensu-extensions-history","version":null,"error":{"path":"sensu/extensions/history","~bt_locations":"#<Thread::Backtrace:0x00000002572dd8>","~mesg":"cannot load such file -- sensu/extensions/history","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:117:in `load_gem'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:30:in `block in load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/daemon.rb:158:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/daemon.rb:58:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:44:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:32:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:32:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/exe/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:22:in `load'","/opt/sensu/bin/sensu-server:22:in `<main>'"]}}
{"timestamp":"2017-07-05T15:05:53.985209+0000","level":"warn","message":"ignoring extension","gem":"sensu-extensions-history"}
{"timestamp":"2017-07-05T15:05:53.985235+0000","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2017-07-05T15:05:53.985254+0000","level":"warn","message":"loaded extension","type":"filter","name":"check_dependencies","description":"filter events when an event exists for a check dependency"}
{"timestamp":"2017-07-05T15:05:53.985291+0000","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2017-07-05T15:05:53.985310+0000","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2017-07-05T15:05:53.985327+0000","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2017-07-05T15:05:53.985343+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2017-07-05T15:05:53.985359+0000","level":"warn","message":"loaded extension","type":"handler","name":"influxdb-extension","description":"Transforms and sends metrics to InfluxDB"}
{"timestamp":"2017-07-05T15:05:53.985430+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2017-07-05T15:05:53.985463+0000","level":"debug","message":"setting eventmachine threadpool size","size":22}
{"timestamp":"2017-07-05T15:05:53.985742+0000","level":"debug","message":"connecting to redis","settings":{"host":"127.0.0.1","port":6379}}
{"timestamp":"2017-07-05T15:05:53.986476+0000","level":"debug","message":"connecting to transport","name":"rabbitmq","settings":{"host":"127.0.0.1","port":5672,"vhost":"/sensu","user":"sensu","password":"secret"}}
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-2.1.0/lib/sensu/extensions/influxdb.rb:34:in `create_config': undefined method `ArgumentError' for #<Sensu::Extension::InfluxDB:0x000000024363e8> (NoMethodError)
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-2.1.0/lib/sensu/extensions/influxdb.rb:83:in `post_init'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:19:in `block in initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:974:in `times'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:33:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'
```

### PR DESCRIPTION
**Pull request by majormoses**
fixes #4 by renaming to be clear which gem this is, needs more work and i re-used some stuff from sensu-plugins that should probably be created for extensions (rubygem user)

### CODE REVIEW

**Comment by majormoses** [comment]
It's not quite functional yet I am working out some issues but wanted to get something we could start working on.

**Comment by luisdavim** [comment]
Yeah, this extension doesn't have any proper tests yet. If I get the chance I can work on that tomorrow.

**Comment by eheydrick** [comment]
I'd add testing on Ruby 2.4.1 too.

**Comment by majormoses** [comment]
@luisdavim I got back to this finally and got things "working" can you please give it a whirl and see if it is all good?

**Comment by majormoses** [comment]
I am currently the owner, @luisdavim whats your user on rubygems.org? @eheydrick @luisdavim we should probably have a larger discussion on either re-using or creating a new user to push extensions as there is not an equivalent to plugins user currently.

**Pull request merged**
